branches:
  except: /^v\d/
language: node_js
matrix:
  include:
  - dist: xenial
    node_js: node
  - os: osx
    node_js: 8
    osx_image: xcode9.3
    script: node test.js
  - os: windows
    node_js: 10
    script: node test.js
